function(osgi_collect_third_party_status package_name package_root platform_tag)
    set(include_dir "${package_root}/include")
    set(lib_dir "${package_root}/${platform_tag}/lib")
    set(bin_dir "${package_root}/${platform_tag}/bin")

    if(WIN32)
        file(GLOB lib_files "${lib_dir}/*.lib")
        file(GLOB bin_files "${bin_dir}/*.dll")
    else()
        file(GLOB lib_files "${lib_dir}/*.a" "${lib_dir}/*.so" "${lib_dir}/*.so.*")
        file(GLOB bin_files "${bin_dir}/*.so" "${bin_dir}/*.so.*")
    endif()

    if(EXISTS "${include_dir}" AND EXISTS "${lib_dir}" AND EXISTS "${bin_dir}" AND lib_files AND bin_files)
        set(found ON)
    else()
        set(found OFF)
    endif()

    set(${package_name}_ROOT "${package_root}" PARENT_SCOPE)
    set(${package_name}_INCLUDE_DIR "${include_dir}" PARENT_SCOPE)
    set(${package_name}_LIB_DIR "${lib_dir}" PARENT_SCOPE)
    set(${package_name}_BIN_DIR "${bin_dir}" PARENT_SCOPE)
    set(${package_name}_FOUND "${found}" PARENT_SCOPE)

    if(found)
        message(STATUS "[third_party] ${package_name}: FOUND (${package_root})")
    else()
        message(STATUS "[third_party] ${package_name}: MISSING (${package_root})")
    endif()
endfunction()
